version: "3.9"

services:
  metadataservice:
    image: ghcr.io/metal-toolbox/hollow-metadaaservice:v0.0.1
    depends_on:
      - crdb
      - metadataservice-migrate
    environment:
      - METADATASERVICE_OIDC_ENABLED=false
      - METADATASERVICE_DB_URI=postgresql://root@crdb:26275/defaultdb?sslmode=disable
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - hollow

  metadataservice-migrate:
    image: ghcr.io/metal-toolbox/hollow-metadataservice:v0.0.1
    command:
      migrate up
    depends_on:
      - crdb
    environment:
      - METADATASERVICE_DB_URI=postgresql://root@crdb:26275/defaultdb?sslmode=disable
    restart: on-failure
    networks:
      - hollow

  crdb:
    image: cockroachdb/cockroach:latest-v21.1
    volumes:
      - db:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
      - "8080:8080"
      - "26257:26257"
    restart: unless-stopped
    networks:
      - hollow

volumes:
  db:

networks:
  hollow:
