wipe = true
pkgname = "models"
output = "internal/models"

[crdb]
dbname = "metadataservice_test"
host = "localhost"
port = 26257
user = "root"
sslmode = "disable"
blacklist = ["goose_db_version"]

[aliases.tables.instance_metadata.columns]
metadata = "Metadata"

[aliases.tables.instance_userdata.columns]
userdata = "Userdata"
